language: android
android:
  components:
    - build-tools-25
    - android-25
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+

script:
    - ./gradlew clean test
    - ./gradlew clean assemble
