language: android
jdk:
    - oraclejdk8
android:
  components:
    - build-tools-25
    - android-25
    - extra-android-m2repository

  licenses:
    - android-sdk-license-.+
    - android-sdk-preview-license-.+
    - google-gdk-license-.+

script:
    - ./gradlew clean test
    - ./gradlew clean assemble
